donate/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name='index'),
    path("donate", views.donate, name='donate'),
    path("dashboard", views.dashboard, name='dashboard'),
    path("login", views.loginPage, name='login'),
    path("logout", views.logoutUser, name='logout'),
    path("signup", views.signup, name='signup'), 
]

plasma/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('donate.urls')),
]

donate/models.py
from django.db import models

DONATE_CENTER=(
    ('1','Donation center 1'),
    ('2','Donation center 2'),
    ('3','Donation center 3')
)

GENDER_CHOICES = (
   ('M', 'Male'),
   ('F', 'Female')
)
BLOOD_GROUP = (
        ('A+','A+'),
        ('A-','A-'),
        ('B+','B+'),
        ('B-','B-'),
        ('O+','O+'),
        ('O-','O-'),
        ('AB+','AB+'),
        ('AB-','AB-')
    )

# Create your models here.
class DonorsInfo(models.Model):
    name = models.CharField(max_length=200, null=True)
    email = models.EmailField(max_length=200, null=True)
    age = models.IntegerField( blank=True, null=True)
    gender = models.CharField(choices=GENDER_CHOICES,max_length=12,default=None)
    blood_group = models.CharField(max_length=3, choices=BLOOD_GROUP, null=True, default=None)
    weight = models.IntegerField(blank=True,null=True)
    negative_tested_on = models.DateField(auto_now=False, auto_now_add=False,null=True)
    city = models.CharField(max_length=200, null=True)
    donate_center = models.CharField(choices=DONATE_CENTER,max_length=12,default=None)
 
    def __str__(self):
        return self.name

donate/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import  DonorsInfo




class CreateUserForms(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

        
        

    

class DonorForms(forms.ModelForm):
    class Meta:
        model = DonorsInfo
        fields = '__all__'
        widgets = {
            'name' : forms.TextInput(attrs={'class': 'form-control'}),
            'email' : forms.EmailInput(attrs={'class': 'form-control'}),
            'age' : forms.NumberInput(attrs={'class': 'form-control'}),
            'gender': forms.RadioSelect(attrs={'class': 'radio'}) ,
            'blood_group': forms.RadioSelect(attrs={'class': 'radio'}), 
            'weight' : forms.NumberInput(attrs={'class': 'form-control'}),
            'negative_tested_on' : forms.DateInput(attrs={'class': 'form-control'}),
            'city' : forms.TextInput(attrs={'class': 'form-control'}),
            'donate_center' : forms.Select(attrs={'class': 'form-select'}),
            }
        

donate/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django.conf import settings
from django.core.mail import send_mail
from django.contrib.auth import authenticate, login ,logout
from django.contrib import messages

from django.contrib.auth.decorators import login_required

# Create your views here.
from .forms import CreateUserForms, DonorForms

from .models import  DonorsInfo

def signup(request):

    if request.user.is_authenticated:
        return redirect('index')
    else:

        form = CreateUserForms()
        if request.method == "POST":
            form = CreateUserForms(request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, "Your account was created " )

            return redirect('index')


        context = {'form': form}
        return render(request, "donate/signup.html", context)

def loginPage(request):
    if request.user.is_authenticated:
        return redirect('index')
    else:
        if request.method =="POST":
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('index')
            else:
                print('login error')

        return render(request, "donate/login.html")

def logoutUser(request):
    logout(request)
    messages.success(request, "You have successfully logout" )
    return redirect('index')

def index(request):
    return render(request, "donate/index.html")

@login_required(login_url='signup')
def donate(request):

    form = DonorForms()
    if request.method == "POST":
        form = DonorForms(request.POST)
        if form.is_valid():
            form.save()
            print("form sent")
            user = form.cleaned_data.get('name')
            messages.success(request, user + ", thank you for your contribution" )
            return redirect('index')
        else: 
            print('form error')
            
    context = {'form': form}
    return render(request, "donate/donate.html", context)



@login_required(login_url='signup')
def dashboard(request):
    name = request.user.username
    data = DonorsInfo.objects.all()
    if request.method == 'POST':
        message = name + ' We have successfully recived your request form Donation center 1.'

        send_mail(
            'Your Request is confirmed😊✨.',
            message,
            settings.EMAIL_HOST_USER,
            [request.user.email],
            fail_silently=False
        )
        messages.success(request, "Your request is sent" )
        return redirect('index')


    
    return render(request, "donate/dashboard.html", {'data': data })

donate/templates/donate/components/navbar.html
{% load static %}
 <nav id="nav" class="navbar navbar-expand-lg navbar-light ">
    <a class="navbar-brand ms-5 py-0  " href="{% url 'index' %}"><img  src="{% static '/donate/green_heart.svg' %}" alt="" width="auto" height="30px"></a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <div id="btn-1" class="col-md-4 text-end">
      {% if user.is_authenticated%}
        <a href="{% url 'logout' %}"><button type="button" class="btn btn-outline-success me-1 py-1 ">Logout</button> </a>
      {% else %}
        <a href="{% url 'login' %}" class="hov"><button type="button" class="btn btn-outline-success me-1 py-1 ">Login</button></a>
        <a href="{% url 'signup' %}" class="hov"><button type="button" class="btn btn-success py-1">Sign-up</button></a>
      {% endif %}
      </div>
    </div>
  </nav>

donate/templates/donate/components/stats.html
<div class="container-fluid ">
  <div class="stats" >
    <div class="card my-1 mx-2 shadow-sm stats-box  " style="width: 11rem">
      <div class="card-body">
        <h5 class="card-title active ">Active</h5>
        <p class="card-text" id="box-1">1</p>
      </div>
    </div>

    <div class="card my-1 mx-2 shadow-sm stats-box " style="width: 11rem">
      <div class="card-body">
        <h5 class="card-title recovered ">Recovered</h5>
        <p class="card-text" id="box-2">2</p>
      </div>
    </div>

    <div class="card my-1 mx-2 shadow-sm stats-box " style="width: 11rem">
      <div class="card-body">
        <h5 class="card-title death ">Death</h5>
        <p class="card-text" id="box-3">3</p>
      </div>
    </div>

    <div class="card my-1 mx-2 shadow-sm stats-box " style="width: 11rem">
      <div class="card-body">
        <h5 class="card-title total">Total</h5>
        <p class="card-text" id="box-4">4</p>
      </div>
    </div>
  </div>
</div>

donate/templates/donate/dashboard.html
{% extends "donate/main.html" %}
{% load static %}

{% block body%}
{% include "donate/components/navbar.html" %}
<script type="text/javascript" src="{% static '/donate/scripts.js' %}"></script>
<div class="backcover">
  <div class="container title fs-4">Donars List</div>
<div class="container">
    <table class="table table-light table-md  table-hover">
        <thead class="">
          <tr>
            
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">Age</th>
            <th scope="col">Gender</th>
            <th scope="col">Blood Group</th>
            <th scope="col">Tested Negative On</th>
            <th scope="col">City</th>
            <th scope="col">Request</th>
          </tr>
        </thead>
        <tbody>
            {% for i in data  %}
          <tr>
            
            <td>{{i.name}}</td>
            <td><div><a href="#">{{i.email}}</a></div></td>
            <td>{{i.age}}</td>
            <td>{{i.gender}}</td>
            <td>{{i.blood_group}}</td>
            <td>{{i.negative_tested_on}}</td>
            <td>{{i.city}}</td> 
            <td >
              <form method="POST" action="{% url 'dashboard' %}">
                {% csrf_token %}
                <input type="submit" name="request" class="offButton" value="Request" >
              </form>
            </td>
            {% endfor %}
            </tr>
          </tbody>
      </table>
      <br>   
</div>
</div>
{% endblock %}

donate/templates/donate/donate.html
{% extends "donate/main.html" %} 
{% load static %}
 {% block body%}
 {% include "donate/components/navbar.html" %}
<div class="backcover">
  <div class="form-contain">
    
    <div class="pb-3 text-md-start fs-2">Plasma Donate</div>
    <form method="POST" action="" class="row g-3">
      {% csrf_token %}
      <div class="col-md-6 mt-1">
        <label class="form-label">Name</label>
        {{form.name }}
      </div>
      <div class="col-md-6 mt-1">
        <label class="form-label">Email</label>
        {{form.email }}
      </div>
      <div class="col-md-6 mt-1">
        <label class="form-label">Age</label>
        {{form.age }}
      </div>
      <div class="form-check col-md-6 mt-1">
        <label class="form-check-label" for="inlineCheckbox1">Gender</label>
        {{form.gender }}
      </div>
      <div class="form-check col-12 mt-1">
        <label class="form-check-label" for="inlineCheckbox1">Blood Group</label>
        {{form.blood_group }}
      </div>
      <div class="col-md-6 mt-1">
        <label class="form-label">Weight</label>
        {{form.weight }}
      </div>
      <div class="col-md-6 mt-1">
        <label class="form-label">Tested negative on</label>
        <img style="position: relative; left: 50%; top: 47%;" src="{% static '/donate/cal.png'%}" width="auto" height="29px" alt="">
        {{form.negative_tested_on }}
      </div>
      <div class="col-md-6 mt-1">
        <label class="form-label">City</label>
        {{form.city }}
      </div>
      <div class="col-md-6 mt-1"></div>
      <div class="col-md-6 mt-1">
        <label class="form-label">Donation Center</label>
        {{form.donate_center }}
      </div>

      <input type="submit" name="Create User" class="submit" value="submit" />
    </form>
    <script>
      $(function () {
        $("#id_negative_tested_on").datepicker({ format: 'mm/dd/yyyy' });
      });
    </script>
  </div >
  
    
  
</div>
{% endblock %}

donate/templates/donate/index.html
{% extends "donate/main.html" %}
{% load static %} 
{% block body%}
<header>
  <div class="top">
    <div class="nav-user">
      {% if user.is_authenticated%}
      <a href="{% url 'logout' %}">logout</a>
      {% else %}
      <a href="{% url 'login' %}">Login</a>
      <a href="{% url 'signup' %}">Sign up</a>
      {% endif %}
    </div>
    {% if messages %}
    <ul style="
      position: relative;
      left: 50%;
      top: 50px; 
      width: 350px;
      border-radius: 4px; 
      border: 2px solid rgb(0, 196, 0); 
      background-color: rgb(239, 253, 239);
      padding: 5px;
      transform: translateX(-50%);
        ">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <div class="px-4 py-5 text-center">
      <img class="d-block mx-auto mb-2" src="{% static '/donate/5.png' %}" alt="" width="auto" height="250px"/>
      <h1 class="display-5 fw-bold">Donate Plasma</h1>
      <div class="col-lg-6 mx-auto">
        <p class="lead mb-4">
          Donating plasma can save lives. Your antibodies can help someone
          fight the infection and emerge victoriously. If your COVID symptoms
          have been absent for more than 14 days, kindly consider donating plasma.
          Just like during any regular blood donation session, blood will be drawn from your arm.
          It will be sent through special tubes that will separate the plasma from the blood.
        </p>
        <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
          <a href="{% url 'donate' %}">
            <button type="button" class="btn btn-light me-sm-2">
              Donar Registration
            </button>
          </a>
          <a href="{% url 'dashboard' %}">
            <button type="button" class="btn btn-outline-dark">
              Register as a Patient
            </button>
          </a>
        </div>
      </div>
    </div>
  </div>
</header>
<section>
  <div class="container">{% include "donate/components/stats.html" %}</div>

  <div class="">
    <div class="bor">
      <div class="index-text">
        <h4>Convalescent plasma</h4>
        Plasma is a component of our blood. Nearly 55% of your blood is plasma. It is yellow in colour. Laboratories can separate plasma from blood with special devices called plasma tubes through a process called centrifugation.
        What makes plasma a candidate for COVID cure is that it contains antibodies. When your body has fought an infection, the antibodies produced are stored in the plasma. That means if you’ve contracted COVID, then antibodies that can fight the COVID infection will be present in your plasma. The plasma from a person who has recovered from a disease is called convalescent plasma.
        Doctors have found evidence that injecting a person who has been infected with COVID with convalescent plasma from someone who has recovered from COVID can help the patient heal faster. 
      </div>
      <div>
        <img class="content-img" src="{% static '/donate/img1.jpg' %}" height="280px" alt="" />
      </div>
    </div>
    <div class="bor">
      <div>
        <img class="content-img" src="{% static '/donate/img2.jpg' %}" height="280px"  alt="" />
      </div>
      <div class="index-text">
        <h4>Who can donate?</h4>
        Well, the first criterion of course is that you need to be a COVID survivor. You can donate 28 days after complete recovery. 
        In India, women between the ages of 18-55 years can donate plasma only if they have never been pregnant.
        All male COVID survivors in the 18-55 age group can donate plasma.
        Donating while you are still battling the infection is not a good idea because you haven’t generated enough antibodies and the ones that you have will be needed by you to kill the virus. 
        According to the FDA, the best time to donate is about 2 weeks after you have completely recovered from your COVID infection. 
      </div>
    </div>
    <div class="bor">
      <div class="index-text">
        <h4>Things to remember before you donate plasma</h4>
        <ul>
          <li>Do not drink alcohol for at least 24 hours before you donate blood.</li>
          <li>Alcohol remains in your system for about a day and end up in the blood that is collected from you.</li>
          <li>Besides alcohol acts as a blood thinner, so there could be a lot of bleeding when you are hooked to the blood extraction device.</li>
          <li>Do not smoke or consume heavy meals/greasy foods before plasma donation.</li>
          <li>Do not pop an aspirin or any kind of pain-relieving medication for 48 hours before the donation. These medicines affect your blood’s platelets.</li>
        </ul> 
        
      </div>
      <div>
        <img class="content-img" src="{% static '/donate/img3.jpg' %}" height="280px"  alt="" />
      </div>
    </div>
  </div>
</section>

{% endblock %}

donate/templates/donate/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en" style="overflow: hidden;">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" type="text/css" href="{% static '/donate/main.css' %}">
  </head>
  <body>
   
    <div class="background ">

        <!-- svg blobs -->
  <svg class="blob-1" viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg" >
    <path fill="#17E6C3" d="M65.6,-52.8C80.6,-33.6,85.1,-6.6,77.5,14.1C69.9,34.7,50.2,49,30.1,56.5C9.9,63.9,-10.7,64.4,-29.1,56.9C-47.5,49.4,-63.6,33.8,-68.2,15.2C-72.7,-3.4,-65.6,-25,-52.3,-43.8C-39,-62.6,-19.5,-78.6,2.9,-80.9C25.3,-83.3,50.7,-72,65.6,-52.8Z" transform="translate(100 100)" />
  </svg>
  <svg class="blob-2" viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
    <path fill="#17E6C3" d="M58,-55.1C72.5,-43.5,79.7,-21.8,76.8,-2.9C73.9,15.9,60.7,31.8,46.3,44.6C31.8,57.4,15.9,67.2,-3.5,70.7C-22.9,74.2,-45.8,71.4,-58.5,58.6C-71.2,45.8,-73.8,22.9,-72.5,1.3C-71.2,-20.3,-66.1,-40.6,-53.3,-52.1C-40.6,-63.6,-20.3,-66.3,0.7,-67.1C21.8,-67.8,43.5,-66.6,58,-55.1Z" transform="translate(100 100)" />
  </svg>
  <div class="blob-3">
    <svg  viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
      <path fill="#17E6C3" d="M43.9,-42.8C56.2,-31.7,64.8,-15.8,65,0.2C65.1,16.2,56.8,32.4,44.6,46.1C32.4,59.9,16.2,71.2,-1,72.2C-18.1,73.2,-36.3,63.8,-52.4,50C-68.4,36.3,-82.4,18.1,-82.6,-0.1C-82.7,-18.4,-68.9,-36.7,-52.8,-47.8C-36.7,-58.9,-18.4,-62.7,-1.3,-61.5C15.8,-60.2,31.7,-53.9,43.9,-42.8Z" transform="translate(100 100)" />
    </svg>


      <div class="card signup-form " style="top: -1%;"> 
        <h3>Login</h3>
        <form action="" method="POST" class="form-margin">
          {% csrf_token %}
          <div class=" mb-2 ">
              <label class="form-label">Username</label>
              <input type="text" aria-label="First name" name="username"  class="form-control "/>
          </div>
          <div class="mb-2">
              <label class="form-label">Password</label>
              <input type="password" aria-label="First name" name="password"  class="form-control"/>
              
            </div>
            
          <input type="submit" value="submit" class="submit" />
        </form>
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
          crossorigin="anonymous"
        ></script>
      </div>
    </div>
  </body>
</html>

donate/templates/donate/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head> 
    
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    
    <!--date picker-->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>
    
    
    <script type="text/javascript" src="{% static '/donate/scripts.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static '/donate/main.css' %}">

</head>
<body >
   

 

    {% block body %}

    {% endblock%}

    <footer>
        <div class="foot"></div>
      </footer>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
</html>

donate/templates/donate/signup.html
<html style="overflow: hidden;">
{% load static %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css"rel="stylesheet"integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6"crossorigin="anonymous"/>
<link rel="stylesheet" type="text/css" href="{% static '/donate/main.css' %}">
{% load crispy_forms_tags %}

<div class="background" >

  <!-- svg blobs -->
  <svg class="blob-1 " viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg" >
    <path fill="#17E6C3" d="M65.6,-52.8C80.6,-33.6,85.1,-6.6,77.5,14.1C69.9,34.7,50.2,49,30.1,56.5C9.9,63.9,-10.7,64.4,-29.1,56.9C-47.5,49.4,-63.6,33.8,-68.2,15.2C-72.7,-3.4,-65.6,-25,-52.3,-43.8C-39,-62.6,-19.5,-78.6,2.9,-80.9C25.3,-83.3,50.7,-72,65.6,-52.8Z" transform="translate(100 100)" />
  </svg>
  <svg class="blob-2 " viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
    <path fill="#17E6C3" d="M58,-55.1C72.5,-43.5,79.7,-21.8,76.8,-2.9C73.9,15.9,60.7,31.8,46.3,44.6C31.8,57.4,15.9,67.2,-3.5,70.7C-22.9,74.2,-45.8,71.4,-58.5,58.6C-71.2,45.8,-73.8,22.9,-72.5,1.3C-71.2,-20.3,-66.1,-40.6,-53.3,-52.1C-40.6,-63.6,-20.3,-66.3,0.7,-67.1C21.8,-67.8,43.5,-66.6,58,-55.1Z" transform="translate(100 100)" />
  </svg>
  <div class="blob-3 ">
    <svg  viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
      <path fill="#17E6C3" d="M43.9,-42.8C56.2,-31.7,64.8,-15.8,65,0.2C65.1,16.2,56.8,32.4,44.6,46.1C32.4,59.9,16.2,71.2,-1,72.2C-18.1,73.2,-36.3,63.8,-52.4,50C-68.4,36.3,-82.4,18.1,-82.6,-0.1C-82.7,-18.4,-68.9,-36.7,-52.8,-47.8C-36.7,-58.9,-18.4,-62.7,-1.3,-61.5C15.8,-60.2,31.7,-53.9,43.9,-42.8Z" transform="translate(100 100)" />
    </svg>

 
<div class="card signup-form ">
  <h3>Register</h3>
<form  method="POST" action="" class="form-margin" >
    {% csrf_token %}
    {{form.username |as_crispy_field }}
    {{form.email |as_crispy_field}}
    {{form.password1 |as_crispy_field}}
    {{form.password2 |as_crispy_field}}
    <input type="submit" name="Create User" class="submit" value="Sign up">
    <p class="already">Already registered? <a href="{% url 'login' %}">Click here</a> to login</p>

  </form>
</div>  
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"crossorigin="anonymous"></script>
</html>